[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ogusa"
version = "0.5.1"
authors = [
    {name = "Jason DeBacker and Richard W. Evans"},
]
description = "USA calibration for OG-Core"
readme = "README.md"
license = "CC0-1.0"
requires-python = ">=3.12, <3.14"
keywords = [
    "USA calibration of large scale overlapping generations model",
    "fiscal policy",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "numpy>=1.26,<2.4",
    "psutil",
    "scipy>=1.7.1",
    "pandas>=1.2.5",
    "matplotlib",
    "dask>=2.30.0",
    "distributed>=2.30.1",
    "paramtools>=0.20.0",
    "taxcalc>=5.2.0",
    "requests",
    "fredapi",
    "xlwt",
    "openpyxl>=3.1.2",
    "statsmodels",
    "linearmodels",
    "ogcore>=0.18.0",
    "tabulate",
]

[project.urls]
Homepage = "https://github.com/PSLmodels/OG-USA/"
"Issue Tracker" = "https://github.com/PSLmodels/OG-USA/issues"

[project.optional-dependencies]
dev = [
    "coverage",
    "pytest>=9.1",
    "pytest-cov",
    "pytest-xdist",
    "ruff",
    "linecheck",
    "ipykernel"
]
docs = [
    "ipykernel",
    "jupyter",
    "jupyter-book<2.0.0",
    "sphinx>=3.5.4",
    "sphinx-book-theme>=0.1.3",
    "sphinxcontrib-bibtex>=2.0.0",
    "tabulate",
]

[tool.setuptools.packages.find]
include = ["ogusa*"]

[tool.setuptools]
include-package-data = false

[tool.setuptools.package-data]
ogusa = [
    "ogusa_default_parameters.json",
    "ogusa_default_parameters_2sector.json",
    "psid_lifetime_income.csv.gz",
    "data/CPS/*.csv",
    "data/SCF/*.pkl",
]

[tool.ruff]
line-length = 79
target-version = "py312"
exclude = [
    "**/*.ipynb",
    "cs-config",
    "docs/book/_build",
    "examples",
]

[tool.ruff.lint]
select = ["E", "F", "W"]
ignore = ["E501", "F841", "W505"]

[tool.ruff.lint.per-file-ignores]
"ogusa/__init__.py" = ["F403"]
"ogusa/calibrate_chi_n.py" = ["E402", "F401"]
"ogusa/get_micro_data.py" = ["F401"]
"ogusa/labor.py" = ["F401", "F821"]
"ogusa/psid_summ_stats.py" = ["F401"]
"ogusa/wealthinit.py" = ["E712", "F401"]

[tool.ruff.lint.pycodestyle]
max-doc-length = 120

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]
markers = [
    "local: marks tests that are run locally only and not on GH Actions",
    "needs_puf: marks tests that require the PUF data to run",
    "needs_tmd: marks tests that require the TMD data to run",
    "needs_fred: marks tests that require a FRED API key to run",
]
